### ISSUE TITLE
The status of switches is hard to see

### ISSUE THREAD

**Issue by Duncank** [JuanMTech/google_dark_theme#1]
![image](https://user-images.githubusercontent.com/719365/72505929-2c91be00-3841-11ea-968e-d6c0768f7a98.png)

In this screenshot, the left switch looks disabled, but is actually switched on; the right switch is turned off but attracts more attention due to the white handle color.

My suggestion would be to style the 'off'-switch like the 'on'-switch looks now, but maybe keep the white handle.
The 'on'-switch could benefit from the blue 'active-state'-color that is being used in the theme, something like this:

![image](https://user-images.githubusercontent.com/719365/72506369-07ea1600-3842-11ea-80c1-297faa0670f5.png)

**Comment by JuanMTech** [comment]
Updated. Thank you for bringing this to my attention.
