### ISSUE TITLE
Add _ to theme name in yaml file

### ISSUE THREAD

**Issue by gregcsw** [JuanMTech/google_dark_theme#10]
Please could you add and under to the theme name inside the theme yaml file.

It is currently

Google Dark Theme:

Change to

Google_Dark_Theme:

This will allow the theme to be set using the service frontend.set_theme, which can then also be used in automations to change the theme.

I have tested the change.

Thanks

**Comment by tigattack** [comment]
The theme can be set using the set_theme service. Put the name in quotes, like this:
`name: "Google Dark Theme"`

**Comment by gregcsw** [comment]
> The theme can be set using the set_theme service. Put the name in quotes, like this:
> `name: "Google Dark Theme"`

Thanks
