### ISSUE TITLE
Some dropdown selectors aren't themed

### ISSUE THREAD

**Issue by tigattack** [JuanMTech/google_dark_theme#12]
The following dropdown selectors aren't themed:
Developer Tools > States > "Entity" dropdown
Developer Tools > Services > "Service" dropdown.

I've not noticed any others so far.

Example:  
![image](https://user-images.githubusercontent.com/10629864/79383179-ac244b80-7f5c-11ea-8b64-f04a94158928.png)

**Comment by tigattack** [comment]
I've also now noticed that various edit/configuration panes in the Home Assistant configuration section aren't themed either. For example:
User edit panes
![image](https://user-images.githubusercontent.com/10629864/79751364-61af2000-830a-11ea-9e68-50c65e23daab.png)
Lovelace dashboard edit panes
![image](https://user-images.githubusercontent.com/10629864/79751428-77bce080-830a-11ea-9ca8-d1d2ab7b3bd7.png)

**Comment by JuanMTech** [comment]
Updated on v1.3

**Comment by tigattack** [comment]
Thanks!
Not quite fixed though; the dropdown selectors in Developer Tools are now themed, but the user and dashboard edit panes that I showed are still unthemed.
