### ISSUE TITLE
addons

### ISSUE THREAD

**Issue by foXaCe** [JuanMTech/google_dark_theme#17]
it possible to fix it ?

![image](https://user-images.githubusercontent.com/290678/81705232-1acacb00-946f-11ea-9f34-ef09cfe600ab.png)

**Comment by foXaCe** [comment]
![image](https://user-images.githubusercontent.com/290678/81705347-3df57a80-946f-11ea-9524-6deeb4eacd79.png)

**Comment by JuanMTech** [comment]
Updated
