### ISSUE TITLE
Color "issue" on Integration

### ISSUE THREAD

**Issue by SeLLeRoNe** [JuanMTech/google_dark_theme#2]
Hi there,
thanks for this theme, it looks very nice :)

I have found only an issue with the phone integration page, somehow it looks with white background rather then the "standard" gray

![image](https://user-images.githubusercontent.com/9599441/72545449-5373e280-3889-11ea-99a1-21d00e76cdc9.png)

**Comment by JuanMTech** [comment]
Updated. Thank you for bringing this to my attention.

**Comment by SeLLeRoNe** [comment]
No worries, thanks for the fix :)
