### ISSUE TITLE
Rounded corners not working properly

### ISSUE THREAD

**Issue by tobiaswrzal** [JuanMTech/google_dark_theme#21]
Hi there,

this is my first issue on GitHub so please be kind with me :)

I installed both the Google Dark and Google Light Theme through HACS as well as manually and in every situation there is an issue with the rounded corners on sensor cards. It looks like the card itself works but the graph overlay stays rectangular. 

You can see that here:
![GoogleTheme](https://user-images.githubusercontent.com/61277294/82091525-cc7c2d00-96f7-11ea-978e-84f9f08f06eb.PNG)

I tried with the current versions of Edge and Chrome and both show this issue.

**Comment by JuanMTech** [comment]
Yeah, that's now something with Home Assistant itself. I don't have control on that. Sorry.
