### ISSUE TITLE
HACS Panel Background Color

### ISSUE THREAD

**Issue by luisiam** [JuanMTech/google_dark_theme#22]
HACS "Information" or "Reinstall" panel background is white. I am running HA 0.110.2 and HACS 1.0.3

![image](https://user-images.githubusercontent.com/16310467/82762132-234acc00-9db4-11ea-8668-04abef195ea5.png)

![image](https://user-images.githubusercontent.com/16310467/82762137-2ba30700-9db4-11ea-8555-880cfba536e7.png)

**Comment by JuanMTech** [comment]
Thank you for bringing this to my attention. It's now fixed with v1.4
