### ISSUE TITLE
Supervisor > Add-ons > Documentation: Light gray text on white background in code blocks

### ISSUE THREAD

**Issue by lghtcrss** [JuanMTech/google_dark_theme#24]
When reading the documentation of installed supervisor add-ons there is hard to read text (light gray on white).
Any tips on how I can fix it?

Thank you.

Example:
<img width="989" alt="example" src="https://user-images.githubusercontent.com/65765024/86885000-c487aa80-c0f4-11ea-97c8-5df95aa8999a.png">

**Comment by JuanMTech** [comment]
Thank you for bringing this to my attention. It's now fixed on v1.6
