### ISSUE TITLE
Gauges numerical value difficult to read

### ISSUE THREAD

**Issue by ioannispelelis** [JuanMTech/google_dark_theme#25]
With this theme the gauges value is difficult to read when there are a lot of numbers/characters
For example if i have a gauge that will show 2000.00 W current power usage (or with other gauges like RAM usage (for example 3000.0 MiB), the first number (2 in the case of the example of power usage) will appear inside the gauge which is usually green. The number itself is white and thus white number on green background is almost not readable.
This happens more on desktop (Chrome) as on mobile the characters seems smaller and take less space and thus do not "invade" in the colored gauge.

**Comment by JuanMTech** [comment]
Can you provide a screenshot so I can check?

**Comment by ioannispelelis** [comment]
@JuanMTech  i cannot reproduce it anymore.. weird. Maybe it got fixed with the latest HA versions and the letters got smaller?

**Comment by JuanMTech** [comment]
Ok. Cool
