### ISSUE TITLE
card-background-colour....... error

### ISSUE THREAD

**Issue by DavidFW1960** [JuanMTech/google_dark_theme#29]
So you didn't replace
```
  paper-card-background-color: var(--card-background-color)
```
with this:
```
  card-background-color: var(--card-background-color)
```
You just deleted it so everything is then white. It might be the mini-media-card using the wrong variable now??? but there doesn't seem to be a reason not to map the paper-card-background-color to map to card-background-color still

**Comment by JuanMTech** [comment]
Working with no issues for me.

**Comment by DavidFW1960** [comment]
You're obviously not using the mini-media-card it's still using paper-card-background-color so I have white boxes on the screen. I suspect there will be more custom cards using old variables as well and there seems to be no reason to remove this at this point.

**Comment by JuanMTech** [comment]
Then is up to the creator of the custom card to update that.

**Comment by DavidFW1960** [comment]
no shit! and I have logged an issue there. My comments still stand!
