### ISSUE TITLE
Latest update broke climate-mini-card appearance

### ISSUE THREAD

**Issue by nanobra1n** [JuanMTech/google_dark_theme#32]
Removal of `paper-card-background-color` in the last update `f68a726` broke the appearance of my climate-mini-card (https://github.com/artem-sedykh/mini-climate-card):
![Screenshot at Jul 29 11-42-05](https://user-images.githubusercontent.com/15968173/88821431-a6abe380-d190-11ea-887a-8a59443fa9d8.png)
Not sure if the card or the theme is to blame, but I am starting with the theme ;)

**Comment by JuanMTech** [comment]
Custom cards need to be updated to the new variable. You can bring up the issue to the custom card GitHub.
