### ISSUE TITLE
Support for dark mode in HA

### ISSUE THREAD

**Issue by andordavoti** [JuanMTech/google_dark_theme#35]
Your themes are really awesome and it'd be awesome to see you add support for light and dark mode. Maybe create a separate theme for it called just "Google Theme"?

**Comment by JuanMTech** [comment]
You can easily set it up by going into *Developer Tools* > *Services* > select `frontend.set_theme` and for the **data** field enter:

```
name: Google Light Theme
mode: Light
```

Then  click on **Call Service**

After that, you can do the same for the dark theme:

```
name: Google Light Theme
mode: Light
```
Then  click on **Call Service** again

**Comment by andordavoti** [comment]
I know you can use it this way, but with home assistant 0.104 it has dark mode support with a single theme. Which means that it respects the system theme of the device.

**Comment by JuanMTech** [comment]
Will check on that. Thanks.
