### ISSUE TITLE
Background of markdown entities isn't black

### ISSUE THREAD

**Issue by hillout** [JuanMTech/google_dark_theme#38]
Hi there,

I've set up the theme and all working fine except this construction: 

style: |
              ha-card {
                box-shadow: none;
                --card-background-color: none
              }

So, the background of the entity isn't that black as it shown at your screenshots. What am I doing wrong? 

Here is a little screenshot of it: 

<img width="454" alt="Снимок экрана 2020-10-15 в 21 58 52" src="https://user-images.githubusercontent.com/15137897/96174392-eaadb980-0f31-11eb-9f93-dc8e15c90a6c.png">

**Comment by JuanMTech** [comment]
The issue is indentation

```
style: |
  ha-card: {
    box-shadow: none;
    --card-background-color: none
  }
```

**Comment by hillout** [comment]
My bad, but not exactly: 

In issue wrote it wrong without indentation, whereas in my config all is as it should be: 

<img width="941" alt="Снимок экрана 2020-10-16 в 11 46 21" src="https://user-images.githubusercontent.com/15137897/96236881-45ccc400-0fa5-11eb-8085-382a17deaf85.png">

**Comment by JuanMTech** [comment]
Do you have the [Card mod](https://github.com/thomasloven/lovelace-card-mod) costume card installed? That's needed for this to work.

**Comment by hillout** [comment]
> Do you have the [Card mod](https://github.com/thomasloven/lovelace-card-mod) costume card installed? That's needed for this to work.

That made the trick. Thank you!
