### ISSUE TITLE
state-icon-color and paper-item-icon-color should match

### ISSUE THREAD

**Issue by arenasa70** [JuanMTech/google_dark_theme#39]
In both Light and Dark themes these colors are inverted:
paper-item-icon-color = state-icon-**active**-color
paper-item-icon-**active**-color =  state-icon-color
Should be: 
paper-item-icon-color = state-icon-color
paper-item-icon-active-color =  state-icon-active-color

**Comment by JuanMTech** [comment]
That's the way I wanted them.
