### ISSUE TITLE
Header Color Changed

### ISSUE THREAD

**Issue by SeLLeRoNe** [JuanMTech/google_dark_theme#4]
Hi there,
with latest update the header color has changed from the dark gray to a light blue
![image](https://user-images.githubusercontent.com/9599441/72606055-2f161580-391e-11ea-8e20-b00110afedc3.png)

I don't believe that was intended, but maybe it can be done customizable? :)

Let me know

Thanks

**Comment by JuanMTech** [comment]
I double-checked on this and it's working correctly. I'm also using the [Custom Header](https://github.com/maykar/custom-header) make sure that you add the following under the `ui-lovelace.yaml`

<pre>
custom_header:
  compact_mode: true
  # Add the below to theme the header
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
</pre>

**Comment by SeLLeRoNe** [comment]
Oh man thanks!

That did it! 

It's odd, before latest update it was already working without the needs of those lines.. go figure... :)

Thanks!
