### ISSUE TITLE
Length/Curvature of Hass.io add-on status indicators

### ISSUE THREAD

**Issue by iophobia** [JuanMTech/google_dark_theme#40]
Hi, great fan of your theme which is running flawlessly on my HA instance. I just noticed recently that in the Supervisor add-on store, the status (line) indicator for installed packages is a bit off in terms of length/curvature (see below).
Thanks,
io
![grafik](https://user-images.githubusercontent.com/21159729/97141178-86bf9800-175e-11eb-9ede-8924c00c1a86.png)

**Comment by JuanMTech** [comment]
That I can't fix. It's now something with HA.
