### ISSUE TITLE
HACS doesn't show dark theme colors properly

### ISSUE THREAD

**Issue by davidrustingha** [JuanMTech/google_dark_theme#42]
As shown in the pictures, in HACS the dark theme isn't shown properly
<img width="643" alt="Screen Shot 2020-11-04 at 17 08 34" src="https://user-images.githubusercontent.com/62120423/98135711-70cd7800-1ec0-11eb-9c1a-02ec042f8041.png">
<img width="1402" alt="Screen Shot 2020-11-04 at 17 08 42" src="https://user-images.githubusercontent.com/62120423/98135726-74f99580-1ec0-11eb-94ce-7a46d0ade56f.png">

**Comment by JuanMTech** [comment]
I haven't use HACS in a while. If this is still happening, I would report it on the HACS site. Not sure what variable they are using for the cards here.
