### ISSUE TITLE
INPUT background color with iOS 15.1 and iPadOS15.1

### ISSUE THREAD

**Issue by emufan** [JuanMTech/google_dark_theme#47]
Starting with iOS 15.1 and iPadOS15.1 the INPUT background color behaves different as before.

![image](https://user-images.githubusercontent.com/22775515/142821903-d4e61203-8e7e-4f1a-bc83-ec0599061f98.png)

This is still the case with latest theme update from today. Andy ideas? Solutions?

Played around somehow with ```paper-input-container-shared-input-style_-_background``` to make the numbers visible again, but then it is still ugly, rounded and still with wihite in the background.

**Comment by JuanMTech** [comment]
It seems to be something related to the iOS app itself.

**Comment by emufan** [comment]
But it is not the case in standard theme. And not only in App, but in Safari as well. 

Don't think core will solve this, because - as said - only in dark custom themes and therefor your theme. 

@JuanMTech Don't understand why this is now closed.
