### ISSUE TITLE
Create a merged theme with both light and dark options

### ISSUE THREAD

**Issue by kzvdar42** [JuanMTech/google_dark_theme#49]
Currently, HA supports light/dark switching inside the custom themes. All you need to do is to create next `.yaml` file:

```
Google Theme:
    modes:
        light: *all changes under google_light_theme*
        dark: *all changes under google_dark_theme*
```

You can find this in the official docs [here](https://www.home-assistant.io/integrations/frontend#dark-mode-support).

After this change it would be possible to change the light/dark themes based on device settings
![image](https://user-images.githubusercontent.com/28705993/146510322-8b477c37-1eda-4ab4-8175-94439d05ca27.png)

**Comment by JuanMTech** [comment]
done. [Link](https://github.com/JuanMTech/google-theme)
