### ISSUE TITLE
Issue with simple-thermostat and mushroom-light-card and mushroom-cover-card

### ISSUE THREAD

**Issue by golles** [JuanMTech/google_dark_theme#50]
I'm using both your light and dark theme with a lot of pleasure, thank you for making and sharing this!

In dark mode only, I have some issues with custom cards. These issues are not with the standard themes.
- On the thermostat card, the grey buttons do not seem to have a background.
- On the light card, the grey circle around the icon and the slider do not seem to have a background.
- On the cover card, the grey circle around the icon and the buttons do not seem to have a background.

On the following screenshots it's obvious to see what I mean:

Dark:
![dark](https://user-images.githubusercontent.com/2211503/154100424-a5cf6d1a-d0f1-4eb3-bde9-e25b70363199.png)

Light:
![light](https://user-images.githubusercontent.com/2211503/154100460-f9288212-2be3-4cf1-b240-bf3220901aca.png)

I'm not sure what else I could share to make it easier to look into this, but I guess the code for the cards might help:
simple-thermostat  source: https://github.com/nervetattoo/simple-thermostat/tree/master/src
mushroom-light-card source: https://github.com/piitaya/lovelace-mushroom/tree/main/src/cards/light-card
mushroom-cover-card source: https://github.com/piitaya/lovelace-mushroom/tree/main/src/cards/cover-card

Let me know if you require more info. Also if this isn't something you want to fix in your themes, I would still appreciate if you can tell me what I could change in the theme locally.

Many thanks!

**Comment by golles** [comment]
The issue with simple-thermostat card I can resolve by changing:
```
secondary-background-color: rgb(32, 33, 36)
```
to:
```
secondary-background-color: rgba(184, 190, 199, 0.4)
```
<img width="500" alt="Schermafbeelding 2022-02-17 om 18 26 38" src="https://user-images.githubusercontent.com/2211503/154537014-596e6b59-0acc-4de3-9e65-891f4cfb8cb7.png">
I don't see that this causes any problems with other UI elements on my UI.

For the mushroom cards I still haven't found a solution

**Comment by golles** [comment]
My previous solution wasn't good, I noticed the dropdown and table on the developer options page didn't look good.

Actually, the thermostat has theming vars, so I could simply fix it by defining a value for `st-mode-background`.

As far as I can see, the mushroom cards use default colors for the icon background and the slider, but I haven't figured out which one that is in the theme

**Comment by JuanMTech** [comment]
It should be fixed now.
