### ISSUE TITLE
Issues with HA 2022.3

### ISSUE THREAD

**Issue by dankocrnkovic** [JuanMTech/google_dark_theme#51]
Hello,

There are number of issues with HA version 2022.3.
Is there something we can do?

![image](https://user-images.githubusercontent.com/78725973/157396192-bd4f449a-a90a-43bb-bffe-634ef6f1072b.png)
![image](https://user-images.githubusercontent.com/78725973/157396273-3a52c8f6-59d9-4753-8639-2a91ff855f11.png)
![image](https://user-images.githubusercontent.com/78725973/157396356-4f761009-72c2-4d37-81e9-c709b7fac586.png)

tnx!
d.

**Comment by etedder** [comment]
Here is a quick fix that you can throw into the yaml:

```
mdc-text-field-fill-color: var(--secondary-background-color)
```

Looks like the latest update introduce a few new Material Design classes that aren't included yet for this theme.

**Comment by dankocrnkovic** [comment]
It did not help. 
Cleared cache after edit. looks the same.

d.

**Comment by etedder** [comment]
Try running the `Home Assistant Frontend: Reload themes` service after making the YAML update

**Comment by dankocrnkovic** [comment]
Nope... did not help.

**Comment by JuanMTech** [comment]
Fixed.
