### ISSUE TITLE
themes folder path

### ISSUE THREAD

**Issue by alexbohariuc** [JuanMTech/google_dark_theme#7]
Hey,

I had an issue on install and I discovered that the themes folder should be included like this:

```
frontend:
  themes: !include_dir_merge_named themes

```
Without navigating to the above folder - since the configuration.yaml is in the same folder as themes.

**Comment by PieBru** [comment]
Confirmed on HA 0.105.6
In my structured YAML configs I use this notation, it has the same effect of the above:
```
frontend:
  themes: !include_dir_merge_named themes/
```

**Comment by HeedfulCrayon** [comment]
I had the same exact issue... had to use
```
frontend:
themes: !include_dir_merge_named themes
```

**Comment by hellofaduck** [comment]
I use in linux  `themes: !include_dir_merge_named ./themes`
@alexbohariuc  you need to change install instruction!

**Comment by JuanMTech** [comment]
If the `themes` folder is just inside of the `Config` folder and not under any other folder then it would be:
````
frontend:
  themes: !include_dir_merge_named themes
````
I'm making the corrections now to the documentation.
