### ISSUE TITLE
Issues with 0.106.2

### ISSUE THREAD

**Issue by JuniorGamingTime** [JuanMTech/google_dark_theme#8]
The panels are white, eveything else seems fine. Some for mobile and on chrome. 
![Screenshot_20200301-005243_Chrome](https://user-images.githubusercontent.com/39572430/75620439-073de280-5b57-11ea-95af-ba56eabbcc56.jpg)

**Comment by JuanMTech** [comment]
Not sure why you are having this issue. I was not able to replicate this on my end. If the issue is still there, try to clear the cache
