### ISSUE TITLE
iOS statusbar

### ISSUE THREAD

**Issue by andordavoti** [JuanMTech/google_dark_theme#9]
Is it possible to make the statusbar black on iOS? Would make the app look a lot better.

![IMG_7BC82C61E9F4-1](https://user-images.githubusercontent.com/24613178/76151628-5932bb00-60b7-11ea-9d86-f126e3293aa2.jpeg)

**Comment by erikvtv** [comment]
I agree, great request. On all other dark apps the statusbar is black or nearly black. Blue bar doesn't reflect a complete black theme.

**Comment by JuanMTech** [comment]
I believe this would be related to the HA app itself. Not the theme

**Comment by matthiasdebaat** [comment]
According to the companion app documents it uses the primary-color for the status bar (https://companion.home-assistant.io/docs/integrations/theming/). 
That’s why it’s the blue color #5F9BAE. 

The companion app should use the app-header-background-color. There is an open issue about this: https://github.com/home-assistant/iOS/issues/558
